### ISSUE TITLE
running julia.Julia() takes 400 seconds.

### ISSUE THREAD

**Issue by jacksonloper** [JuliaInterop/pyjulia#37]
If you want to exactly replicate, use amazon ec2, image ami-9a562df2 (aka the official ubuntu 14.04 image), machine m3.medium, solid-state drive, provisioned with docker by vagrant.  Then build this Dockerfile:

	FROM ipython/scipyserver

	# install julia from the approved ppa, and get pycall
	RUN apt-get install -y software-properties-common python-software-properties \
	 && add-apt-repository -y ppa:staticfloat/juliareleases \
	 && apt-get update \
	 && apt-get install -y julia \
	 && julia -e 'Pkg.resolve(); Pkg.update(); Pkg.add("PyCall")'

	# install pyjulia
	RUN git clone https://github.com/JuliaLang/pyjulia.git \
	 && pip3 install ./pyjulia 

	# run it, and wait.  a long time :).
	CMD python3 -c "import julia,time,sys; print('starting!'); sys.stdout.flush(); t=time.time(); j=julia.Julia(); print(time.time()-t);  print('done')"
    
Running the resulting docker image should yield results like this:

	ubuntu@ip-172-30-4-223:~$ docker images
	REPOSITORY            TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
	soslow                latest              61ba5988405a        13 minutes ago      2.874 GB
	ipython/scipyserver   latest              9a23ce264f79        12 hours ago        2.651 GB
	ubuntu@ip-172-30-4-223:~$ docker run --rm soslow
	starting!
	403.7160954475403
	done
	ubuntu@ip-172-30-4-223:~$ docker run --rm soslow
	starting!
	401.85526943206787
	done
	ubuntu@ip-172-30-4-223:~$ docker run --rm soslow
	starting!
	403.40179347991943
	done

While it is running, the command is using 100% of the cpu.    

* I experience the same phenomena working from the base image library/python, so I don't think it's that.  
* I experience the same phenomena if I install pip3 on the ec2 machine and then use those Dockerfile instructions to directly provision the ec2 machine (without using docker).   That is,

        ubuntu@ip-172-30-4-223:~$ python3 -c "import julia,time,sys; print('starting'); sys.stdout.flush(); t=time.time(); j=julia.Julia(); print(time.time()-t);  print('done')"
        starting
        402.0854015350342
        done

* I experience the same phenomena running python2.7 instead of python3.4.
* Every once and while, it is modestly reasonable (20 seconds).  But then it goes back to being very slow.  The behavior appears random, which is very disturbing :).  

Why is nobody else experiencing this??  I must be doing something dreadfully wrong!

**Comment by jakebolewski** [comment]
Oh no!  Wow that is pretty bad.

Loading pyjulia is slow because it has to start PyCall after initializing Julia.  @stevengj any ideas what is happening here that may be contributing to the performance?

@jacksonloper have you tried timing spinning up Julia and then loading PyCall as a point of reference?

```shell
time julia -e "using PyCall; exit(0)"
```

**Comment by jacksonloper** [comment]
Loading pycall is slow (e.g. 7 seconds), but not 400 seconds slow :).

**Comment by stonebig** [comment]
what happen if you try replacing `pyinitialize(C_NULL)` per `pyinitialize()` ?

**Comment by jakebolewski** [comment]
Are you up for some `strace`ing?   I'll have to download the docker image and have a look.  One more question would be,  when installing the docker file locally on your computer (in a VM) do you see the same behavior or is this only on EC2?

**Comment by jacksonloper** [comment]
1) If I replace pyinitialize(C_NULL) with pyinitialize in the pyjulia master, I get a "couldn't get stack" PyError.  Which I think isn't surprising since I think it would probably end up trying to create two python interpreters.  

2) If I run it on my local machine, I get the same behavior.  The only reason I went to the cloud was because I assumed it was something somehow profoundly broken with my machine :).

3) Don't know much about strace.  But I just ran 

        strace python3 -c "import julia,time,sys; print('starting'); sys.stdout.flush(); t=time.time(); j=julia.Julia(); print(time.time()-t);  print('done')"

    The strace seems to hang on some of the 500-ish calls to `brk` (slightly different pattern each time).  But top never shows more than 1% of my RAM being used by the process, so I don't think it's actually some kind of swapping issue.   The brk calls follow a call to `rt_sigprocmask(SIG_BLOCK,NULL,[],8)` .  The most recent file opened was `/root/.julia/v0.3/PyCall/src/io.jl`.

**Comment by Keno** [comment]
A lot has changed on master, and I have never seen this. If this occurs again, please comment here and I'll reopen.
