### ISSUE TITLE
Executing Julia Script

### ISSUE THREAD

**Issue by parth9615** [JuliaInterop/pyjulia#50]
Is there any way to exceute and entire Julia file using the pyjulia package?

**Comment by mmagnuski** [comment]
Julia has `include` command that does that so you could try calling include using pyjulia. Unfortunatelly I can't help more - pyjulia doesn't work on my windows machine. But if you want to use pyjulia with julia 0.4 on mac/linux - be sure to check [this pull request](https://github.com/JuliaLang/pyjulia/pull/47).

**Comment by Keno** [comment]
Yes, calling `include` is the right way to go.
