### ISSUE TITLE
Python version error when creating julia object

### ISSUE THREAD

**Issue by sondree** [JuliaInterop/pyjulia#57]
I am attempting to get pyjulia to run on Linux mint 17.3 (Ubuntu derivative).  I have installed latest version of Julia from precompiled repositories (official) and latest version of pyjulia from Github.

Loading the pyjulia module works, but creating a Julia object results in the following output:

>import julia

>  j = julia.Julia()
> ErrorException("Using pyjulia with a statically-compiled version\nof python or with a version of python that\ndiffers from that used by PyCall.jl is not\nsupported on julia 0.4")Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "julia/core.py", line 332, in __init__
>     """)
>   File "julia/core.py", line 392, in _call
>     self.check_exception(src)
>   File "julia/core.py", line 412, in check_exception
>     .format(exception_type, src))
> julia.core.JuliaError: Exception 'ErrorException' occurred while calling julia code:
> 
>                     if VERSION < v"0.5-"
>                         error("""Using pyjulia with a statically-compiled version
>                                   of python or with a version of python that
>                                   differs from that used by PyCall.jl is not
>                                   supported on julia 0.4""")
>                     end
>                 

I have both python2.7 and python3 installed but the python shell above was started using python2.7. 

Further debugging against the error message lead me to the option of specifying the python version used by PyCall (Julia package). 

In a Julia shell:

> ENV["PYTHON"] = "/usr/bin/python2.7"
> Pkg.build("PyCall")
> using PyCall

This does not resolve the problem. The specific python version I am using is 2.7.6 and Julia version 0.4.6

Any assistance would be appreciated.

**Comment by Keno** [comment]
Output of `ldd /usr/bin/python2.7`?

**Comment by sondree** [comment]
> ldd /usr/bin/python2.7

> 	linux-vdso.so.1 =>  (0x00007ffe2c516000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5523d72000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f55239ad000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f55237a8000)
> 	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f55235a5000)
> 	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f552338c000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5523085000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f5523fb4000)
>

**Comment by Keno** [comment]
Yep, statically linked as expected, so not supported on 0.4

**Comment by sondree** [comment]
Well that was exceedingly unhelpful. How do I go about addressing this/getting a non-statically linked python? Do I have to install/compile a custom python binary? 

This should be part of the readme as I am running a bog standard setup and it is highly unlikely that I am the only one facing this issue.

**Comment by Keno** [comment]
Having this work at all is a new feature only available on julia 0.5 as the error message says. You may either upgrade julia or get a dynamically compiled version of python. How to do the latter will depend on your OS, or you may have to compile a custom version as you suggested.

**Comment by sondree** [comment]
That is helpful, thank you.

 May I suggest rephrasing the error message if that is the intended message. As it stands I got the impressing that the only way to fix the issue is to get another python interpreter. Maybe adding "Either upgrade Julia to 0.5+ or install a dynamically linked python binary" would be good?

**Comment by sondree** [comment]
Upgrading Julia to latest nightly dev build fixes the previous issue but presents a new issue.

> Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
> [GCC 4.8.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
>  import julia
> 
>  j = julia.Julia()
> WARNING: redefining constant JULIA_HOME
> INFO: Recompiling stale cache file /home/falense/.julia/lib/pyjulia2-v0.5/PyCall.ji for module PyCall.
> Traceback (most recent call last):
>   File "/home/falense/Julia/pyjulia/fake-julia/julia.py", line 17, in <module>
>     libjulia.jl_parse_opts.argtypes = [POINTER(c_int), POINTER(POINTER(c_char_p))]
>   File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
>     func = self.__getitem__(name)
>   File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
>     func = self._FuncPtr((name_or_ordinal, self))
> AttributeError: /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so: undefined symbol: jl_parse_opts
> write: broken pipe (EPIPE)Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "julia/core.py", line 353, in __init__
>     self._call(u"using PyCall")
>   File "julia/core.py", line 392, in _call
>     self.check_exception(src)
>   File "julia/core.py", line 412, in check_exception
>     .format(exception_type, src))
> julia.core.JuliaError: Exception 'UVError' occurred while calling julia code:
> using PyCall
> 

Output from Julia:

> 
>    _       _ _(_)_     |  A fresh approach to technical computing
>   (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
>    _ _   _| |_  __ _   |  Type "?help" for help.
>   | | | | | | |/ _` |  |
>   | | |_| | | | (_| |  |  Version 0.5.0-dev+3438 (2016-04-07 15:46 UTC)
>  _/ |\__'_|_|_|\__'_|  |  Commit a92c7ff (108 days old master)
> |__/                   |  x86_64-linux-gnu
> 
> julia> Pkg.add("PyCall")
> INFO: Initializing package repository /home/falense/.julia/v0.5
> INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
> INFO: Installing BinDeps v0.4.0
> INFO: Installing Compat v0.8.6
> INFO: Installing Conda v0.2.2
> INFO: Installing JSON v0.6.0
> INFO: Installing MacroTools v0.3.0
> INFO: Installing PyCall v1.6.3
> INFO: Installing SHA v0.1.2
> INFO: Installing URIParser v0.1.5
> INFO: Building PyCall
> INFO: PyCall is using python (Python 2.7.6) at /usr/bin/python, libpython = libpython2.7
> INFO: Package database updated
> 
> julia> ENV["PYTHON"] = "/usr/bin/python2.7"
> "/usr/bin/python2.7"
> 
> julia> Pkg.build("PyCall")
> INFO: Building PyCall
> INFO: PyCall is using /usr/bin/python2.7 (Python 2.7.6) at /usr/bin/python2.7, libpython = libpython2.7
> 
> 
> 
>

**Comment by sondree** [comment]
I guess missing "jl_parse_opts" is an error in the current Julia build?

**Comment by Keno** [comment]
The julia 0.5 build is not recent enough.

**Comment by sondree** [comment]
Same error with Julia built from Github sources, this should be bleeding edge. Is there an even more recent version?
